name: Build & Deploy Laravel

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '8.1'
  #         extensions: mbstring, xml, ctype, fileinfo, bcmath, json
  #         coverage: none

  #     - name: Install Composer dependencies
  #       run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

  #     - name: Install Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install NPM dependencies
  #       run: npm install

  #     - name: Set Laravel Vite bypass environment variable
  #       run: echo "LARAVEL_BYPASS_ENV_CHECK=1" >> $GITHUB_ENV

  #     - name: Build production assets
  #       run: npm run build  # Build for production

  #     - name: Generate optimized Laravel files
  #       run: |
  #         php artisan config:cache
  #         php artisan route:cache
  #         php artisan view:cache

  #     - name: Upload built files for deployment
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: laravel-app
  #         path: |
  #           vendor
  #           node_modules
  #           public/css
  #           public/js
  #           bootstrap/cache
  #           storage/framework/cache
  #           storage/framework/sessions
  #           storage/framework/views

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # - name: Download built files
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: laravel-app
      #     path: ./
          
      - name: Check GitHub Token Length
        run: |
          echo "TOKEN length: ${#TOKEN} characters"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      # - name: Add SSH key
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_KEY }}

      # - name: Check SSH Key Length
      #   run: |
      #     echo "SSH_KEY length: ${#SSH_KEY} characters"
      - name: Deploy to Server
        run: |
          echo $SSH_KEY
          # Uncomment the following lines when you configure SSH
          # ssh -i $SSH_KEY user@yourserver 'cd /path/to/your/project && git pull && php artisan migrate --force'
